language: java
jdk: openjdk11
cache:
  directories:
    - "$HOME/.m2/repository"
env:
  COMPOSE_VERSION: 1.5.2
  
before_install:
  - docker-compose pull
  - docker-compose up
  
after_success:
  - bash <(curl -s https://codecov.io/bash)
# script:
#   - mvn clean package -DskipTests=true


