version: '2'

services:

  mongo:
    image: mongo:3.4-jessie
    ports:
      - 27017:27017
    expose:
      - 27017
    container_name: mongonew
    network_mode: host
    volumes:
      - /mongo-volume:/data/db


  db:
    image: mysql:5.7
    restart: always
    container_name: mysqlnew
    network_mode: "host"
    hostname: localhost
    volumes:
      - '/mysql-volume:/var/lib/mysql'
    environment:
      MYSQL_DATABASE: jwtdb
      # So you don't have to use root, but you can if you like
      # Password for root access
      MYSQL_ROOT_PASSWORD: Root@123
    ports:
      # <Port exposed> : < MySQL Port running inside container>
      - 3306:3306


  eureka-server:
    build: eureka-server/
    restart: always
    network_mode: "host"
    hostname: localhost
    ports:
      - 8761:8761


  config-service:
    build: config-server/
    restart: always
    network_mode: "host"
    hostname: localhost
    ports:
      - 8888:8888


  zuul-apigateway:
    build: zuul-api/
    depends_on:
      - config-service
      - eureka-server
    restart: always
    network_mode: "host"
    hostname: localhost
    ports:
      - 8080:8080

    mem_reservation: 100m

  subscription-service:
    build: subscription-service/
    restart: always
    network_mode: "host"
    hostname: localhost
    ports:
      - 9003:9003



  enrollment:
    build: enrollment/
    restart: always
    network_mode: "host"
    hostname: localhost
    depends_on:
      - config-service
      - eureka-server
      - mongo
    ports:
      - 8091:8091


  program-schedular:
    build: program-schedular/
    restart: always
    network_mode: "host"
    hostname: localhost
    depends_on:
      - config-service
      - eureka-server
      - mongo
    ports:
      - 8092:8092



  program-service:
    build: program-service/
    restart: always
    network_mode: "host"
    hostname: localhost
    depends_on:
      - config-service
      - eureka-server
      - mongo
    ports:
      - 9001:9001



  jwtfirst:
    build: user-authentication-service/
    restart: always
    network_mode: "host"
    hostname: localhost
    depends_on:
      - config-service
      - eureka-server
      - db
    ports:
      - 9002:9002



  rabbitmq:
    image: "rabbitmq:3-management"
    hostname: "rabbit"
    ports:
       - "15672:15672"
       - "5672:5672"
    labels:
       NAME: "rabbitmq"
